### ISSUE TITLE
咨询相关事宜

### ISSUE THREAD

**Issue by ShadyWhite** [menphina/Milvaneth#1]
您好，今天刚刚发现这个项目，请问这个项目还在维护并进行测试吗，想咨询公开时间和ACT Overlay合作方面事宜

**Comment by Chigusa0w0** [comment]
本项目我不再维护了。在4.55的时候进行过完整的测试，5.0的时候进行过基础的测试。目前的公开结果将是这个项目的“最终状态”。

> 由于种种个人原因，我认为目前自己无法独自将此项目部署为一个公共免费服务。因此，我决定公开既有代码以供后来者参考。

> 特此免费授予获得该软件和相关文档文件副本的任何人基于该项目的修改或未修改的版本设置免费或收费服务的权利。

> Milvaneth 项目的源代码以 MIT/X11 许可证分发。

**Comment by ShadyWhite** [comment]
了解了，多谢解答
